# Customer Churn Modelling using ANN

In [8]:
#!pip install theano
#!pip install tensorflow

In [103]:
#import theano
import tensorflow
import keras
import numpy as np
import pandas as pd

In [104]:
from keras.models import Sequential
from keras.layers import Dense

In [122]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [106]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [107]:
data.shape

(10000, 14)

In [108]:
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [109]:
label_encoder_x_country = LabelEncoder()
x[:,1] = label_encoder_x_country.fit_transform(x[:,1])

label_encoder_x_gender = LabelEncoder()
x[:,2] = label_encoder_x_gender.fit_transform(x[:,2])
x
#
#

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [110]:
onehot_encoder = OneHotEncoder(categorical_features=[1])

In [111]:
x = onehot_encoder.fit_transform(x).toarray()

In [112]:
x = x[:,1:]
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [113]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [114]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [115]:
classifer = Sequential()
classifer.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform" ))

In [116]:
classifer.add(Dense(activation="relu", units=6, kernel_initializer="uniform" ))

In [117]:
classifer.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform" ))

In [118]:
classifer.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [119]:
classifer.fit(x_train,y_train,batch_size=10,epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4853 - acc: 0.7931
Epoch 2/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4343 - acc: 0.7934
Epoch 3/100
8000/8000 [==============================] - 1s 79us/step - loss: 0.4285 - acc: 0.8005
Epoch 4/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4246 - acc: 0.8229
Epoch 5/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.4224 - acc: 0.8276
Epoch 6/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4206 - acc: 0.8276
Epoch 7/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4194 - acc: 0.8296
Epoch 8/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.4182 - acc: 0.8305: 0s - loss: 0.4414 - 
Epoch 9/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4169 - acc: 0.8316
Epoch 10/100
8000/8000 [=============

8000/8000 [==============================] - 1s 76us/step - loss: 0.4060 - acc: 0.8326
Epoch 79/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4055 - acc: 0.8321
Epoch 80/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.4062 - acc: 0.8341
Epoch 81/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4056 - acc: 0.8331
Epoch 82/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.4057 - acc: 0.8331
Epoch 83/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4060 - acc: 0.8335
Epoch 84/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.4052 - acc: 0.8345
Epoch 85/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4058 - acc: 0.8337
Epoch 86/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.4054 - acc: 0.8345
Epoch 87/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4058 - acc: 0.8317
Epoch 88/100


In [135]:
y_pred.flatten()
y_test
comp = pd.DataFrame({'Actual':y_test,'Predicted':y_pred.flatten()})
comp.head()

Actual  Predicted
0       1       True
1       0      False
2       0       True
3       0      False
4       0      False

In [120]:
y_pred = classifer.predict(x_test)
y_pred = y_pred > 0.5

In [126]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1548,   68],
       [ 245,  139]], dtype=int64)

In [137]:
accuracy = (1548+139)/2000
accuracy

0.8435